service: not-that-movie
runtime: python311

instance_class: F2

env_variables:
  ENV: prod

service_account: not-that-movie-worker@webhost-common.iam.gserviceaccount.com

entrypoint: gunicorn -b :$PORT app:app
